version: '3.8'

x-environment: &default-environment
  MINIO_ACCESS_KEY: eoVnEUo0TjVwo5ltsQcI
  MINIO_SECRET_KEY: g0pHa6qD2RNL8JIXgVaL8Xl2FYf06tTfqGHPgXED
  MINIO_ENDPOINT_URL: "http://api_s3:9000"

services:
  s3_worker:
    build: .
    container_name: s3_worker
    environment:
      <<: [ *default-environment ]
      MINIO_ENDPOINT_URL: http://host.docker.internal:9000
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  api_s3:
    image: minio/minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      <<: [ *default-environment ]
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - s3-data_volume:/data


volumes:
  s3-data_volume:
