version: '3.8'

services:
  s3_worker:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.biwork-s3_worker.rule=Host(`api.files.biwork.tech`)"
      - "traefik.http.routers.biwork-s3_worker.entrypoints=http,https"
      - "traefik.http.routers.biwork-s3_worker.tls.certresolver=myresolver"
      - "traefik.http.services.biwork-s3_worker.loadbalancer.server.port=8000"
      - "traefik.http.routers.biwork-s3_worker.service=biwork-s3_worker"

    networks:
      - traefik

  api_s3:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.biwork-api_s3.rule=Host(`files.biwork.tech`)"
      - "traefik.http.routers.biwork-api_s3.entrypoints=http,https"
      - "traefik.http.routers.biwork-api_s3.tls.certresolver=myresolver"
      - "traefik.http.services.biwork-api_s3.loadbalancer.server.port=9000"
      - "traefik.http.routers.minio-console.service=minio-console"
      - "traefik.http.routers.minio-console.tls.certresolver=myresolver"
      - "traefik.http.routers.minio-console.rule=Host(`minio.biwork.tech`)"
      - "traefik.http.services.minio-console.loadbalancer.server.port=9001"

    networks:
      - traefik

networks:
  traefik:
    external: true